name: referencer # you probably want to 'snapcraft register <name>'
version: '1.2.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: manage your bibliograpy # 79 char long summary
description: manage your bibliograpy

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./referencer-1.2.2/data/referencer.svg

apps:
  referencer:
    command: desktop-launch $SNAP/bin/referencer
    desktop: share/applications/referencer.desktop
    environment:
      PYTHONPATH: $SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/python2.7/:$SNAP/usr/lib/python2.7/plat-x86_64-linux-gnu/:$SNAP/lib/referencer/:$PYTHONPATH
      PYTHONHOME: $SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib/python2.7/:/$SNAP/usr/lib/python2.7/plat-x86_64-linux-gnu/:/$SNAP/lib/referencer/:$PYTHONHOME
#      datadir: $SNAP/share/referencer/
#      datarootdir: $SNAP/share/referencer/
#      prefixe: $SNAP/
    plugs: 
        - x11
        - home
        - desktop
        - network
    
parts:
  referencer:
    # See 'snapcraft plugins'
    plugin: autotools   
    source: ./referencer-1.2.2/
#    organize:
#      share/referencer : data/
    after: 
        - desktop-gtk2
    build-packages:
        - build-essential
        - gnome-doc-utils
        - intltool
        - python2.7-dev
        - libpython2.7-dev
        - libxml2-dev
        - libpoppler-glib-dev
        - libgconfmm-2.6-dev
        - libgtkmm-2.4-dev
        - libboost-regex-dev
        - rarian-compat
        
    stage-packages:
        - libc6
        - libatkmm-1.6-1v5
        - libcairomm-1.0-1v5
        - libdbus-glib-1-2
        - libgconf-2-4
        - libdb5.3
        - libgconfmm-2.6-1v5
        - libpangomm-1.4-1v5
        - libglibmm-2.4-1v5
        - libpoppler-glib8
        - libpoppler58
        - python2.7
        - libpython2.7
        - libgtkmm-2.4-1v5
        - libboost-regex1.58.0
        - libsigc++-2.0-0v5
        
#  python-plugins:
#    source: ./referencer-1.2.2/plugins/
#    plugin: python
#    python-version: 'python2'
#    stage-packages:
#        - python-gobject
#        - python-gi
    
